// src/pages/dashboard/CalendrierAcademique.tsx
import React, { useEffect, useMemo, useState } from "react";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import listPlugin from "@fullcalendar/list";

import api from "@/lib/api";
import ScheduleForm from "@/components/forms/ScheduleForm";

import type { ScheduleType } from "@/types/schedule";
import type { ModuleType } from "@/types/module";
import type { TeacherType } from "@/types/teacher";
import type { PromotionType } from "@/types/promotion";

/**
 * CalendrierAcademique.tsx
 * - Tolérance aux réponses API (data ou tableau direct)
 * - Priorité couleur : schedule.color -> module.color -> couleur générée stable
 * - Filtres enseignant / promotion
 * - Modal form (create / edit / delete) via ScheduleForm component
 */

const CalendrierAcademique: React.FC = () => {
  const [schedules, setSchedules] = useState<ScheduleType[]>([]);
  const [modules, setModules] = useState<ModuleType[]>([]);
  const [teachers, setTeachers] = useState<TeacherType[]>([]);
  const [promotions, setPromotions] = useState<PromotionType[]>([]);

  // selectedSchedule typed as any to accept both API shapes and in-flight objects
  const [selectedSchedule, setSelectedSchedule] = useState<any | null>(null);
  const [openForm, setOpenForm] = useState(false);

  const [filterTeacher, setFilterTeacher] = useState<string>("all");
  const [filterPromotion, setFilterPromotion] = useState<string>("all");

  // ---------- Helpers ----------
  const safeArray = <T,>(maybe: unknown): T[] => {
    if (!maybe) return [];
    if (Array.isArray(maybe)) return maybe as T[];
    if (typeof maybe === "object" && maybe !== null && "data" in (maybe as any)) {
      const d = (maybe as any).data;
      return Array.isArray(d) ? (d as T[]) : [];
    }
    return [];
  };

  // stable color generation from string (id)
  const colorFromString = (s?: string | number | null) => {
    const str = String(s ?? "");
    if (!str) return "#0066ff";
    let h = 0;
    for (let i = 0; i < str.length; i++) h = str.charCodeAt(i) + ((h << 5) - h);
    let color = "#";
    for (let i = 0; i < 3; i++) {
      const value = (h >> (i * 8)) & 0xff;
      color += ("00" + value.toString(16)).slice(-2);
    }
    return color;
  };

  // Choose color: schedule.color -> module.color -> generated by id
  const getEventColor = (sch: any, mod?: any) => {
    if (sch?.color) return sch.color;
    if (mod?.color) return mod.color;
    // try module nested in schedule
    if (sch?.module?.color) return sch.module.color;
    return colorFromString(mod?.id ?? sch?.moduleId ?? sch?.id ?? sch?.title);
  };

  // ---------- Load data ----------
  const loadData = async () => {
    try {
      const [schRes, modRes, teachRes, promoRes] = await Promise.all([
        api.get("/schedules"),
        api.get("/modules"),
        api.get("/teachers"),
        api.get("/promotions"),
      ]);

      setSchedules(safeArray<ScheduleType>(schRes?.data));
      setModules(safeArray<ModuleType>(modRes?.data));
      setTeachers(safeArray<TeacherType>(teachRes?.data));
      setPromotions(safeArray<PromotionType>(promoRes?.data));
    } catch (err) {
      console.error("Erreur chargement calendrier:", err);
      // Keep UI resilient — leave arrays empty
    }
  };

  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ---------- Calendar handlers ----------
  // select => create new schedule object
  const handleSelect = (info: any) => {
    const start = info.startStr ?? info.start;
    const end = info.endStr ?? info.end;

    setSelectedSchedule({
      id: undefined,
      title: "",
      moduleId: null,
      teacherId: null,
      promotionId: null,
      start,
      end,
      room: "",
      type: "",
      color: "",
      notes: "",
      module: null,
      teacher: null,
      promotion: null,
    });

    setOpenForm(true);
  };

  const handleEventClick = (info: any) => {
    const eventId = info.event?.id;
    if (!eventId) return;

    // Try to find schedule by id
    const schedule = schedules.find((s: any) => String(s.id) === String(eventId));
    if (schedule) {
      setSelectedSchedule(schedule);
    } else {
      // fallback: use extendedProps
      const ext = info.event?.extendedProps ?? {};
      setSelectedSchedule({
        id: eventId,
        title: info.event?.title ?? "",
        start: info.event?.start ?? null,
        end: info.event?.end ?? null,
        ...ext,
      });
    }
    setOpenForm(true);
  };

  // ---------- Filters ----------
  const filteredSchedules = useMemo(() => {
    return schedules.filter((s: any) => {
      const okTeacher = filterTeacher === "all" || String(s.teacherId) === String(filterTeacher);
      const okPromotion = filterPromotion === "all" || String(s.promotionId) === String(filterPromotion);
      return okTeacher && okPromotion;
    });
  }, [schedules, filterTeacher, filterPromotion]);

  // ---------- Map to FullCalendar events ----------
  const calendarEvents = useMemo(() => {
    return filteredSchedules.map((s: any) => {
      const mod = modules.find((m: any) => String(m.id) === String(s.moduleId));
      const teacher = teachers.find((t: any) => String(t.id) === String(s.teacherId));
      const promo = promotions.find((p: any) => String(p.id) === String(s.promotionId));

      const titleParts = [s.title || ""];
      if (mod?.title) titleParts.push(mod.title);
      if (teacher?.username || (teacher?.nom && teacher?.prenom)) {
        titleParts.push(teacher?.username ?? `${teacher?.nom ?? ""} ${teacher?.prenom ?? ""}`.trim());
      }
      if (promo?.nom) titleParts.push(promo.nom);

      const color = getEventColor(s, mod);

      return {
        id: s.id,
        title: titleParts.filter(Boolean).join(" — "),
        start: s.start,
        end: s.end,
        backgroundColor: color,
        borderColor: color,
        extendedProps: {
          schedule: s,
          module: mod ?? null,
          teacher: teacher ?? null,
          promotion: promo ?? null,
        },
      };
    });
    // only depend on arrays (shallow)
  }, [filteredSchedules, modules, teachers, promotions]);

  // ---------- Render ----------
  return (
    <div className="p-4">
      <h1 className="text-xl font-bold mb-4">Calendrier Académique</h1>

      {/* Filters */}
      <div className="flex flex-wrap gap-4 mb-4">
        <div>
          <label className="block text-sm font-medium mb-1">Filtrer par enseignant</label>
          <select
            className="border p-2 rounded"
            value={filterTeacher}
            onChange={(e) => setFilterTeacher(e.target.value)}
          >
            <option value="all">Tous les enseignants</option>
            {Array.isArray(teachers) &&
              teachers.map((t: any) => (
                <option key={String(t.id)} value={String(t.id)}>
                  {t.username ?? `${t.nom ?? ""} ${t.prenom ?? ""}`.trim()}
                </option>
              ))}
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">Filtrer par promotion</label>
          <select
            className="border p-2 rounded"
            value={filterPromotion}
            onChange={(e) => setFilterPromotion(e.target.value)}
          >
            <option value="all">Toutes les promotions</option>
            {Array.isArray(promotions) &&
              promotions.map((p: any) => (
                <option key={String(p.id)} value={String(p.id)}>
                  {p.nom ?? `Promotion ${p.id}`}
                </option>
              ))}
          </select>
        </div>
      </div>

      {/* Calendar */}
      <FullCalendar
        plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin, listPlugin]}
        initialView="dayGridMonth"
        selectable={true}
        editable={false}
        height="80vh"
        events={calendarEvents}
        select={handleSelect}
        eventClick={handleEventClick}
        headerToolbar={{
          left: "prev,next today",
          center: "title",
          right: "dayGridMonth,timeGridWeek,timeGridDay,listWeek",
        }}
        eventTimeFormat={{
          hour: "2-digit",
          minute: "2-digit",
          hour12: false,
        }}
      />

      {/* Modal / Form */}
      {openForm && (
        <ScheduleForm
          schedule={selectedSchedule}
          modules={Array.isArray(modules) ? modules : []}
          teachers={Array.isArray(teachers) ? teachers : []}
          promotions={Array.isArray(promotions) ? promotions : []}
          onClose={() => {
            setOpenForm(false);
            setSelectedSchedule(null);
          }}
          onSaved={async () => {
            setOpenForm(false);
            setSelectedSchedule(null);
            await loadData();
          }}
        />
      )}
    </div>
  );
};

export default CalendrierAcademique;
